/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  eminencerp: [
    'acceuil',
    // {
    //   type: 'category',
    //   label: 'Tutorial',
    //   items: ['tutorial-basics/create-a-document', 'tutorial-basics/create-a-blog-post'],
    // },
  ],
  
  developpement: [
    'Catalogues/intro',
    // {
    //   type: 'category',
    //   label: 'Tutorial',
    //   items: ['tutorial-basics/create-a-document', 'tutorial-basics/create-a-blog-post'],
    // },
  ],
  touches: [
    'Catalogues/intro',
    // {
    //   type: 'category',
    //   label: 'Tutorial',
    //   items: ['tutorial-basics/create-a-document', 'tutorial-basics/create-a-blog-post'],
    // },
  ],
  reglements: [
    'Règlements/Introduction',
    'Règlements/Sanctions',
    'Règlements/Stream',
    'Règlements/Remboursement',
    'Règlements/Discord',
    // {
    //   type: 'category',
    //   label: 'Tutorial',
    //   items: ['tutorial-basics/create-a-document', 'tutorial-basics/create-a-blog-post'],
    // },
  ],
  catalogues: [
    'Catalogues/intro',
    // {
    //   type: 'category',
    //   label: 'Tutorial',
    //   items: ['tutorial-basics/create-a-document', 'tutorial-basics/create-a-blog-post'],
    // },
  ],
   
};

module.exports = sidebars;
